apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: teq-sentry-claim
  name: teq-sentry-claim
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 60Gi
  storageClassName: "local-storage"
  volumeName: "teq-sentry-pv"
status: {}
