apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: teq-sentry-redis-claim
    app: redis
    heritage: Tiller
    release: teq-sentry
  name: teq-sentry-redis-claim
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
  storageClassName: "local-storage"
  volumeName: "redis-data-teq-sentry"
status: {}